### ISSUE TITLE
Tidak Bisa Run 

### ISSUE THREAD

**Issue by DKPST404** [EtcAug10/Domaineer#1]
Checking connection availability in service 1
Traceback (most recent call last):
  File "/storage/emulated/0/DCIM/Domaineer/domaineer.py", line 65, in <module>
    Main()
  File "/storage/emulated/0/DCIM/Domaineer/domaineer.py", line 19, in __init__
    self.inputassign()
  File "/storage/emulated/0/DCIM/Domaineer/domaineer.py", line 47, in inputassign
    reverseip()
  File "/storage/emulated/0/DCIM/Domaineer/tool/core.py", line 246, in reverseip
    conn.get(ips[0])
AttributeError: 'OsintSH' object has no attribute 'get'

**Comment by c0del1ar** [comment]
Sudah diperbaiki. Coba update tool dengan pull request pada folder "/storage/emulated/0/DCIM/Domaineer/"

git pull https://github.com/EtcAug10/Domaineer
